function extractHostname(b){b=-1<b.indexOf("://")?b.split("/")[2]:b.split("/")[0];b=b.split(":")[0];return b=b.split("?")[0]}function extractRootDomain(b){b=extractHostname(b);var a=b.split("."),c=a.length;2<c&&(b=("com"===a[c-2]||"net"===a[c-2]||"co"===a[c-2])&&3<=c?a[c-3]+"."+a[c-2]+"."+a[c-1]:a[c-2]+"."+a[c-1]);return b}
var getClosestTop=function(){var b=window,a=!1;try{for(;b.parent.document!==b.document;)if(b.parent.document)b=b.parent;else{a=!0;break}}catch(c){a=!0}return{topFrame:b,err:a}},getBestPageUrl=function(b){var a=b.topFrame,c="";if(b.err)try{try{c=window.top.location.href}catch(f){var e=window.location.ancestorOrigins;c=e[e.length-1]}}catch(f){c=a.document.referrer}else c=a.location.href;return c},TOPFRAMEOBJ=getClosestTop(),PAGE_URL=getBestPageUrl(TOPFRAMEOBJ);
function showMoreGames(){0<jQuery("#more-games-button").length&&jQuery("#more-games-button").fadeIn()}function hideMoreGames(){0<jQuery("#more-games-button").length&&jQuery("#more-games-button").fadeOut()}
function checkMoreGames(b){var a=getGames(extractRootDomain(PAGE_URL));0!==a.length&&(jQuery("body").append('<div id="more-games-button"></div>'),jQuery("#more-games-button").on("click",function(){var b="<div class='more-games-dialog-wrapper'><div class='more-games-dialog-block'></div><div class='more-games-dialog-content'><div class='more-games-dialog-scrolling'>";for(var e=0;e<a.length;e++)b+="<a target='_blank' class='more-games-dialog-tile' href='"+a[e].url+"'>",b+="<img src='"+a[e].img+"' />",
b+="</a>";b+="</div><div class='embed-and-earn'><a href='http://gamedistribution.com/publishers/' target='_blank'>Earn with</br>our games</a><a target='_blank' href='http://gamedistribution.com/Gamelist/Code-This%20Lab%20srl/'>Embed<br>our games</a></div><a href='http://gamedistribution.com/Gamelist/Code-This%20Lab%20srl/'><div class='more-games-dialog-logo'></div></a></div><div class='more-games-dialog-exit'></div></div>";jQuery("body").append(b);setTimeout(function(){jQuery(".more-games-dialog-block").addClass("more-games-dialog-block-show");
setTimeout(function(){jQuery(".more-games-dialog-content").addClass("more-games-dialog-content-show");jQuery(".more-games-dialog-exit").addClass("more-games-dialog-exit-show")},100)},100)}),jQuery("#more-games-button").fadeIn())}
$(document).ready(function(){jQuery(document).on("click",".more-games-dialog-exit",function(){jQuery(".more-games-dialog-content").removeClass("more-games-dialog-content-show");jQuery(".more-games-dialog-exit").removeClass("more-games-dialog-exit-show");setTimeout(function(){jQuery(".more-games-dialog-block").removeClass("more-games-dialog-block-show");setTimeout(function(){jQuery(".more-games-dialog-wrapper").remove()},500)},100)})});
function getGames(b){var a=[];switch(b){case "codethislab.com":case "gamedistribution.com":a.push({img:"http://img.gamedistribution.com/8f2d0e8b584d4eb5930a5158d08d163b.jpg",url:"http://gamedistribution.com/Games/Shoot-'Em-Up/Dead-City.html"});a.push({img:"http://img.gamedistribution.com/57acee2e2934416ea24a8c1c5a9ed8ea.jpg",url:"http://gamedistribution.com/Games/Shooter/King-Bacon-VS-Vegans.html"});a.push({img:"http://img.gamedistribution.com/fb59e2712b664e3d8c4d7decfcf419c9.jpg",url:"http://gamedistribution.com/Games/Action/Cyclops-Ruins.html"});
a.push({img:"http://img.gamedistribution.com/4bf984a368a64b11a2748da4c66bcaa2.jpg",url:"http://gamedistribution.com/Games/Board/Mastermind.html"});a.push({img:"http://img.gamedistribution.com/4d081fdaff874976a47e3ec80ad9a393.jpg",url:"http://gamedistribution.com/Games/Soccer/Penalty-Kicks.html"});a.push({img:"http://img.gamedistribution.com/0f38da229ce44294b5aeaa52771b1608.jpg",url:"http://gamedistribution.com/Games/Soccer/Foosball.html"});a.push({img:"http://img.gamedistribution.com/28aad67b0b39407c93b372e83cb8cc88.jpg",
url:"http://gamedistribution.com/Games/Racing/Greyhound-Racing.html"});a.push({img:"http://img.gamedistribution.com/902ee2d7bef446d79fde28bb28cd0f01.jpg",url:"http://gamedistribution.com/Games/Match-3/Frogtastic.html"});a.push({img:"http://img.gamedistribution.com/7b35c3ce549b408abe37f77990d7f6fa.jpg",url:"http://gamedistribution.com/Games/Board/Nine-Mens-Morris.html"});a.push({img:"http://img.gamedistribution.com/a4c67fbbc9bb4d70a26a85a91e5d12cc.jpg",url:"http://gamedistribution.com/Games/Classic/Neon-Pong.html"});
a.push({img:"http://img.gamedistribution.com/3ab6d797bf8340139483367ac2dbf76b.jpg",url:"http://gamedistribution.com/Games/Racing/Gear-Madness.html"});a.push({img:"http://img.gamedistribution.com/c2820a1635844cff8c6c9b2bf0771df0.jpg",url:"http://gamedistribution.com/Games/Addicting/2048--Cuteness-Edition.html"});a.push({img:"http://img.gamedistribution.com/d96dc07738f248c49ae51c61facd4286.jpg",url:"http://gamedistribution.com/Games/1-Player/Classic-Backgammon.html"});a.push({img:"http://img.gamedistribution.com/f360e5b43093401ca1b9a6d54105ffd2.jpg",
url:"http://gamedistribution.com/Games/Golf/Minigolf-World.html"});a.push({img:"http://img.gamedistribution.com/4ba63b68f15a4ecbb21eef429655dcc0.jpg",url:"http://gamedistribution.com/Games/Board/Domino-Block.html"});a.push({img:"http://img.gamedistribution.com/9881ac54b4ac48ad8b6fd92232e5ed4f.jpg",url:"http://gamedistribution.com/Games/Jigsaw-Puzzle/Jigsaw-Deluxe.html"});a.push({img:"http://img.gamedistribution.com/b2a3398e327b4f6da665759d6730aab4.jpg",url:"http://gamedistribution.com/Games/Chess/Master-Chess.html"});
a.push({img:"http://img.gamedistribution.com/a82bfcc90a8548a3976b0b2d13dd37dd.jpg",url:"http://gamedistribution.com/Games/Puzzle/Free-Words.html"});a.push({img:"http://img.gamedistribution.com/d7b10d9e32844525a0bfa1fef7324895.jpg",url:"http://gamedistribution.com/Games/Board/Connect-4.html"});a.push({img:"http://img.gamedistribution.com/36b470b1f113447696c2704c6e1bd0c2.jpg",url:"http://gamedistribution.com/Games/Skill/Snake-and-Blocks.html"});a.push({img:"http://img.gamedistribution.com/e0d570df45e146899b986770297c0210.jpg",
url:"http://gamedistribution.com/Games/Board/Master-Checkers.html"});a.push({img:"http://img.gamedistribution.com/2cea016521ab452692a0141a40dfde9b.jpg",url:"http://gamedistribution.com/Games/Sports/Swimming-Pro.html"});a.push({img:"http://img.gamedistribution.com/3be284e237de4c7ba3a9e5cac0fd6ee3.jpg",url:"http://gamedistribution.com/Games/Soccer/Freekick-Training.html"});break;case "a10.com":a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",url:"http://www.a10.com/popular-games/snake-and-blocks"});
a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",url:"http://www.a10.com/action-games/swimming-pro"});break;case "10000paixnidia.gr":a.push({img:"http://media.bfgfile.com/images/33_2121d.jpg",url:"http://www.10000paixnidia.gr/paixnidia/connect_4"});a.push({img:"http://media.bfgfile.com/images/35_49441.jpg",url:"http://www.10000paixnidia.gr/paixnidia/frogtastic-mobile"});a.push({img:"http://media.bfgfile.com/images/32_49279d.jpg",url:"http://www.10000paixnidia.gr/paixnidia/minigolf-world"});
break;case "10001games.fr":a.push({img:"http://media.bfgfile.com/images/33_2121d.jpg",url:"http://www.10001games.fr/jeu/connect_4"});a.push({img:"http://media.bfgfile.com/images/35_49441.jpg",url:"http://www.10001games.fr/jeu/frogtastic-mobile"});a.push({img:"http://media.bfgfile.com/images/32_49279d.jpg",url:"http://www.10001games.fr/jeu/minigolf-world"});break;case "1001paixnidia.eu":a.push({img:"http://media.bfgfile.com/images/33_2121d.jpg",url:"http://www.1001paixnidia.eu/paixnidia/connect_4"});
a.push({img:"http://media.bfgfile.com/images/35_49441.jpg",url:"http://www.1001paixnidia.eu/paixnidia/frogtastic-mobile"});a.push({img:"http://media.bfgfile.com/images/32_49279d.jpg",url:"http://www.1001paixnidia.eu/paixnidia/minigolf-world"});break;case "101games.it":a.push({img:"http://media.bfgfile.com/images/33_2121d.jpg",url:"http://www.101games.it/giochi/connect_4"});a.push({img:"http://media.bfgfile.com/images/35_49441.jpg",url:"http://www.101games.it/giochi/frogtastic-mobile"});a.push({img:"http://media.bfgfile.com/images/32_49279d.jpg",
url:"http://www.101games.it/giochi/minigolf-world"});break;case "agame.com":a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",url:"http://www.agame.com/game/snake-and-blocks/"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",url:"http://www.agame.com/game/swimming-pro"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",url:"http://www.agame.com/game/connect-4-classic"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-1/200X120_170521_1503068454.png",
url:"http://www.agame.com/game/master-checkers"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-1-9/200X120_170519_1503065531.png",url:"http://www.agame.com/game/domino-block"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-4-1/200X120_170541_1503321513.png",url:"http://www.agame.com/game/classic-backgammon-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",url:"http://www.agame.com/game/free-words"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",
url:"http://www.agame.com/game/jigsaw-deluxe"});break;case "bebekoyunu.com.tr":a.push({img:"http://m.bebekoyunu.com.tr/img/s/cadde-yarisi-cilginlari-4582.jpg",url:"http://bebekoyunu.com.tr/cadde-yarisi-cilginlari-oyna.html"});a.push({img:"http://m.bebekoyunu.com.tr/img/s/domino-4525.jpg",url:"http://bebekoyunu.com.tr/domino-oyna.html"});a.push({img:"http://m.bebekoyunu.com.tr/img/s/2-kisilik-satranc-4509.jpg",url:"http://www.bebekoyunu.com.tr/2-kisilik-satranc-oyna.html"});a.push({img:"http://m.bebekoyunu.com.tr/img/s/tavla-4519.jpg",
url:"http://bebekoyunu.com.tr/2-kisilik-tavla-oyna.html"});a.push({img:"http://m.bebekoyunu.com.tr/img/s/matematik-yilani-2-4505.jpg",url:"http://www.bebekoyunu.com.tr/matematik-yilani-2-oyna.html"});break;case "bgames.com":a.push({img:"http://static.bgames.com/games/assets/icons/3/112243/89539/bggb-380662.jpg",url:"http://www.bgames.com/sport-games/minigolf_world/"});break;case "clickjogos.com.br":a.push({img:"http://img2.clickjogos.com.br/dl/3/3294ff9b92437bc8c3dae81514e8895b/thumb.png?1504543080",
url:"http://www.clickjogos.com.br/jogos/penalty-kicks/"});a.push({img:"http://img2.clickjogos.com.br/dl/b/be63e6dca8c799105962f9f110090fad/thumb.png?1504125627",url:"http://www.clickjogos.com.br/jogos/gear-madness/"});a.push({img:"http://img5.clickjogos.com.br/dl/b/bd6a0ccee7cba8dd6c1f2fbe611654d7/thumb.png?1504108745",url:"http://www.clickjogos.com.br/jogos/freekick-training/"});break;case "flashgames.ru":a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",url:"http://www.flashgames.ru/igra/soberi-4-klassika"});
a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",url:"http://www.flashgames.ru/igra/zmeia-i-bloki"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",url:"http://www.flashgames.ru/igra/chempion-po-plavaniiu"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-1/200X120_170521_1503068454.png",url:"http://www.flashgames.ru/igra/master-shashek"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-1-9/200X120_170519_1503065531.png",url:"http://www.flashgames.ru/igra/blok-domino"});
a.push({img:"http://files.cdn.spilcloud.com/thumbs-4-1/200X120_170541_1503321513.png",url:"http://www.flashgames.ru/igra/classic-backgammon-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",url:"http://www.flashgames.ru/igra/mir-svobodnykh-slov"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",url:"http://www.flashgames.ru/igra/pazl-deliuks"});break;case "frivjogosonline.com.br":a.push({img:"http://cdn.frivjogosonline.com.br/wp-content/files/08/jpg/1f02a80db7d63ff04a6986023d3a0b60-120x100.jpg",
url:"http://www.frivjogosonline.com.br/jogo/freekick-training.html"});break;case "funnygames.be":a.push({img:"http://assets.funnygames.be/games/assets/promos/3/112243/89539/185x145-380649.jpg",url:"http://www.funnygames.be/spel/minigolf.html"});break;case "funnygames.nl":a.push({img:"http://assets.funnygames.nl/games/assets/promos/7/19057/72449/185x145-380370.jpg",url:"http://www.funnygames.nl/spel/vier_op_een_rij.html"});a.push({img:"http://assets.funnygames.nl/games/assets/promos/2/112582/90773/185x145-380398.jpg?r=1502108077054",
url:"http://www.funnygames.nl/spel/free_words.html"});break;case "funnygames.us":a.push({img:"http://assets.funnygames.us/games/assets/screenshots/3/112243/89539/minigolf-world-pss-380643.jpg",url:"http://www.funnygames.us/game/minigolf_world.html"});a.push({img:"http://assets.funnygames.us/games/assets/screenshots/7/19057/72449/connect-4-pss-225028.jpg?r=1502092710859",url:"http://www.funnygames.us/game/connect_4.html"});break;case "game-game.com":a.push({img:"http://cdn2.game-game.com.ua/gamesimg/180909.jpg",
url:"http://www.game-game.com.ua/180909/"});a.push({img:"http://cdn2.game-game.com.ua/gamesimg/180384_big.jpg",url:"http://game-game.com/180384/"});break;case "game-game.com.ua":a.push({img:"http://cdn1.game-game.com.ua/gamesimg/180909_big.jpg",url:"http://game-game.com/180909/"});a.push({img:"http://www.game-game.com.ua/gamesimg/180384.jpg",url:"http://www.game-game.com.ua/180384/"});break;case "game-game.kz":a.push({img:"http://cdn1.game-game.com.ua/gamesimg/180909_big.jpg",url:"http://game-game.kz/180909/"});
a.push({img:"http://www.game-game.com.ua/gamesimg/180384.jpg",url:"http://game-game.kz/180384/"});break;case "game-game.lv":a.push({img:"http://cdn1.game-game.com.ua/gamesimg/180909_big.jpg",url:"http://game-game.lv/180909/"});a.push({img:"http://www.game-game.com.ua/gamesimg/180384.jpg",url:"http://game-game.lv/180384/"});break;case "game-game.ma":a.push({img:"http://cdn1.game-game.com.ua/gamesimg/180909_big.jpg",url:"http://game-game.ma/180909/"});a.push({img:"http://www.game-game.com.ua/gamesimg/180384.jpg",
url:"http://game-game.ma/180384/"});break;case "games.co.id":a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",url:"http://www.games.co.id/permainan_/hubungkan-4-klasik"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",url:"http://www.games.co.id/permainan_/ular-dan-balok"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",url:"http://www.games.co.id/permainan_/renang-profesional"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-1/200X120_170521_1503068454.png",
url:"http://www.games.co.id/permainan_/master-checker"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-1-9/200X120_170519_1503065531.png",url:"http://www.games.co.id/permainan_/balok-domino"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-4-1/200X120_170541_1503321513.png",url:"http://www.games.co.id/permainan_/classic-backgammon-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",url:"http://www.games.co.id/permainan_/kata-kata-bebas"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",
url:"http://www.games.co.id/permainan_/puzzle-jigsaw-deluks"});break;case "games.co.uk":a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",url:"http://www.games.co.uk/game/connect-4-classic"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",url:"http://www.games.co.uk/game/snake-and-blocks"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",url:"http://www.games.co.uk/game/swimming-pro"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-1/200X120_170521_1503068454.png",
url:"http://www.games.co.uk/game/master-checkers"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-1-9/200X120_170519_1503065531.png",url:"http://www.games.co.uk/game/domino-block"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-4-1/200X120_170541_1503321513.png",url:"http://www.games.co.uk/game/classic-backgammon-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",url:"http://www.games.co.uk/game/free-words"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",
url:"http://www.games.co.uk/game/jigsaw-deluxe"});break;case "games.do":a.push({img:"http://media.bfgfile.com/images/33_2121d.jpg",url:"http://www.games.do/games/connect_4"});a.push({img:"http://media.bfgfile.com/images/35_49441.jpg",url:"http://www.games.do/games/frogtastic-mobile"});a.push({img:"http://media.bfgfile.com/images/32_49279d.jpg",url:"http://www.games.do/games/minigolf-world"});break;case "gamesgames.com":a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",
url:"http://www.gamesgames.com/game/connect-4-classic"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",url:"http://www.gamesgames.com/game/snake-and-blocks"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",url:"http://www.gamesgames.com/game/swimming-pro"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-1/200X120_170521_1503068454.png",url:"http://www.gamesgames.com/game/master-checkers"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-1-9/200X120_170519_1503065531.png",
url:"http://www.gamesgames.com/game/domino-block"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-4-1/200X120_170541_1503321513.png",url:"http://www.gamesgames.com/game/classic-backgammon-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",url:"http://www.gamesgames.com/game/free-words"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",url:"http://www.gamesgames.com/game/jigsaw-deluxe"});break;case "gameshed.com":a.push({img:"http://games.gameshed.com/dead-city.jpg",
url:"http://www.gameshed.com/Zombie-Games/Dead-City/"});break;case "games.gr":a.push({img:"http://media.games.gr/images/32_49279d.jpg",url:"http://www.games.gr/search/minigolf/"});a.push({img:"http://media.games.gr/images/33_2121d.jpg",url:"http://www.games.gr/paixnidia/connect_4"});a.push({img:"http://media.games.gr/images/35_49441.jpg",url:"http://www.games.gr/paixnidia/frogtastic-mobile"});break;case "gioco.it":a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",
url:"http://www.gioco.it/gioco/connect-4-classico"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",url:"http://www.gioco.it/gioco/blocchi-e-serpenti"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",url:"http://www.gioco.it/gioco/swimming-pro"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-1/200X120_170521_1503068454.png",url:"http://www.gioco.it/gioco/dama-royale"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-1-9/200X120_170519_1503065531.png",
url:"http://www.gioco.it/gioco/dominoblock"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-4-1/200X120_170541_1503321513.png",url:"http://www.gioco.it/gioco/classic-backgammon-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",url:"http://www.gioco.it/gioco/parole-in-liberta"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",url:"http://www.gioco.it/gioco/puzzle-deluxe"});break;case "giochi.it":a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",
url:"http://www.giochi.it/gioco/connect-4-classico"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",url:"http://www.giochi.it/gioco/blocchi-e-serpenti"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",url:"http://www.giochi.it/gioco/swimming-pro"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-1/200X120_170521_1503068454.png",url:"http://www.giochi.it/gioco/dama-royale"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-1-9/200X120_170519_1503065531.png",
url:"http://www.giochi.it/gioco/dominoblock"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-4-1/200X120_170541_1503321513.png",url:"http://www.giochi.it/gioco/classic-backgammon-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",url:"http://www.giochi.it/gioco/parole-in-liberta"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",url:"http://www.giochi.it/gioco/puzzle-deluxe"});break;case "giochigratisonline.it":a.push({img:"http://www.giochigratisonline.it/giochi-online/giochi-vari/snake-and-blocks/snake.jpg",
url:"http://www.giochigratisonline.it/giochi-online/giochi-vari/snake-and-blocks/"});break;case "girlsgogames.co.uk":a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",url:"http://www.girlsgogames.co.uk/game/connect-4-classic"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",url:"http://www.girlsgogames.co.uk/game/snake-and-blocks"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",url:"http://www.girlsgogames.co.uk/game/swimming-pro"});
a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",url:"http://www.girlsgogames.co.uk/game/free-words"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",url:"http://www.girlsgogames.fr/jeu/puzzle-de-luxe"});break;case "girlsgogames.fr":a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",url:"http://www.girlsgogames.fr/jeu/puzzle-de-luxe"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",
url:"http://www.girlsgogames.fr/jeu/mots-gratuits"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",url:"http://www.girlsgogames.fr/jeu/puissance-4-classique"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",url:"http://www.girlsgogames.fr/jeu/serpent-vs-blocs-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",url:"http://www.girlsgogames.fr/jeu/pro-de-la-natation"});break;case "girlsgogames.ru":a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",
url:"http://www.girlsgogames.ru/igra/pazl-deliuks"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",url:"http://www.girlsgogames.ru/igra/soberi-4-klassika"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",url:"http://www.girlsgogames.ru/igra/mir-svobodnykh-slov"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",url:"http://www.girlsgogames.ru/igra/zmeia-i-bloki"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",
url:"http://www.girlsgogames.ru/igra/chempion-po-plavaniiu"});break;case "gratisspil.dk":a.push({img:"http://www.gratisspil.dk/9394/onlineGameImages/w140/1504259771nmm.png",url:"http://www.gratisspil.dk/onlineGame/games/play.php?categoryID=7&id=6224#commentsPaginatorPage=1"});break;case "gry.pl":a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",url:"http://www.gry.pl/gra/weze-i-bloki"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",
url:"http://www.gry.pl/gra/swimming-pro"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",url:"http://www.gry.pl/gra/poacz-4-wersja-klasyczna"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-1/200X120_170521_1503068454.png",url:"http://www.gry.pl/gra/mistrzowskie-warcaby"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-1/200X120_170521_1503068454.png",url:"http://www.gry.pl/gra/mistrzowskie-warcaby"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-1-9/200X120_170519_1503065531.png",
url:"http://www.gry.pl/gra/zagraj-w-domino"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-4-1/200X120_170541_1503321513.png",url:"http://www.gry.pl/gra/classic-backgammon-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",url:"http://www.gry.pl/gra/darmowe-sowa"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",url:"http://www.gry.pl/gra/puzzle-luksusowe"});break;case "hierspielen.com":a.push({img:"http://www.hierspielen.com/img/games/200x150/23088.jpg",
url:"http://www.hierspielen.com/spiel/frogtastic.html"});break;case "juegos.com":a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",url:"http://www.juegos.com/juego/conecta-4-clasico"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",url:"http://www.juegos.com/juego/serpientes-y-bloques"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",url:"http://www.juegos.com/juego/nadador-profesional"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-1/200X120_170521_1503068454.png",
url:"http://www.juegos.com/juego/damas-maestras"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-1-9/200X120_170519_1503065531.png",url:"http://www.juegos.com/juego/bloques-de-domino"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-4-1/200X120_170541_1503321513.png",url:"http://www.juegos.com/juego/classic-backgammon-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",url:"http://www.juegos.com/juego/palabras-libres"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",
url:"http://www.juegos.com/juego/rompecabezas-de-lujo"});break;case "jeja.pl":a.push({img:"http://pobierak.jeja.pl/games_thumb/c/d/0/36215_200x120.jpg?1504101426",url:"http://www.gry.jeja.pl/36215,trening-rzutow-wolnych.html"});break;case "jetztspielen.de":a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",url:"http://www.jetztspielen.de/spiel/vier-gewinnt-klassisch"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",url:"http://www.jetztspielen.de/spiel/schlange-und-blocke"});
a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",url:"http://www.jetztspielen.de/spiel/swimming-pro"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-1/200X120_170521_1503068454.png",url:"http://www.jetztspielen.de/spiel/meister-in-dame"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-1-9/200X120_170519_1503065531.png",url:"http://www.jetztspielen.de/spiel/domino-block"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-4-1/200X120_170541_1503321513.png",url:"http://www.jetztspielen.de/spiel/classic-backgammon-"});
a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",url:"http://www.jetztspielen.de/spiel/freie-worter"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",url:"http://www.jetztspielen.de/spiel/puzzle-deluxe"});break;case "jeu.fr":a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",url:"http://www.jeu.fr/jeu/puissance-4-classique"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",
url:"http://www.jeu.fr/jeu/serpent-vs-blocs-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",url:"http://www.jeu.fr/jeu/pro-de-la-natation"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-1/200X120_170521_1503068454.png",url:"http://www.jeu.fr/jeu/maitre-aux-echecs"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-1-9/200X120_170519_1503065531.png",url:"http://www.jeu.fr/jeu/bloc-de-dominos"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-4-1/200X120_170541_1503321513.png",
url:"http://www.jeu.fr/jeu/classic-backgammon-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",url:"http://www.jeu.fr/jeu/mots-gratuits"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",url:"http://www.jeu.fr/jeu/puzzle-de-luxe"});break;case "jeux.fr":a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",url:"http://www.jeux.fr/jeu/puissance-4-classique"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",
url:"http://www.jeux.fr/jeu/serpent-vs-blocs-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",url:"http://www.jeux.fr/jeu/pro-de-la-natation"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-1/200X120_170521_1503068454.png",url:"http://www.jeux.fr/jeu/maitre-aux-echecs"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-1-9/200X120_170519_1503065531.png",url:"http://www.jeux.fr/jeu/bloc-de-dominos"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-4-1/200X120_170541_1503321513.png",
url:"http://www.jeux.fr/jeu/classic-backgammon-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",url:"http://www.jeux.fr/jeu/mots-gratuits"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",url:"http://www.jeux.fr/jeu/puzzle-de-luxe"});break;case "k2t2.com":a.push({img:"http://k2t2.com/content/upload/games/images/minigolf-world.png",url:"http://k2t2.com/minigolf-world/"});a.push({img:"http://k2t2.com/content/upload/games/images/snake-and-blocks.png",
url:"http://k2t2.com/snake-and-blocks/"});break;case "klikarnia.pl":a.push({img:"http://klikarnia.pl/gryonline/frogtastic.jpg",url:"http://klikarnia.pl/frogtastic"});break;case "igry-multiki.ru":a.push({img:"http://www.igry-multiki.ru/contents/image/games/game/220x165/shashki-na-planshet-igry-b.jpg",url:"http://www.igry-multiki.ru/igra-shashki-na-planshet/"});a.push({img:"http://www.igry-multiki.ru/contents/image/games/game/220x165/shahmaty-na-planshet-igry-b.jpg",url:"http://www.igry-multiki.ru/igra-shahmaty-na-planshet/"});
break;case "mousebreaker.com":a.push({img:"http://files.cdn.spilcloud.com/thumbs-4-1/200X120_170541_1503321513.png",url:"http://www.mousebreaker.com/game/classic-backgammon-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-1-9/200X120_170519_1503065531.png",url:"http://www.mousebreaker.com/game/domino-block"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",url:"http://www.mousebreaker.com/game/swimming-pro"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",
url:"http://www.mousebreaker.com/game/free-words"});break;case "minioyun.org":a.push({img:"http://www.minioyun.org/img/baglanti-4-klasik.JPG",url:"http://www.minioyun.org/baglanti-4-klasik.html"});break;case "ojogos.com.br":a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",url:"http://www.ojogos.com.br/jogo/connect-4-classico"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",url:"http://www.ojogos.com.br/jogo/cobra-e-blocos"});
a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",url:"http://www.ojogos.com.br/jogo/swimming-pro"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-1/200X120_170521_1503068454.png",url:"http://www.ojogos.com.br/jogo/maioral-das-damas"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-1-9/200X120_170519_1503065531.png",url:"http://www.ojogos.com.br/jogo/bloco-de-domino"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-4-1/200X120_170541_1503321513.png",url:"http://www.ojogos.com.br/jogo/classic-backgammon-"});
a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",url:"http://www.ojogos.com.br/jogo/palavras-livres"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",url:"http://www.ojogos.com.br/jogo/quebra-cabecas-de-luxo"});break;case "ourgames.ru":a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",url:"http://www.ourgames.ru/igra/soberi-4-klassika"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",
url:"http://www.ourgames.ru/igra/zmeia-i-bloki"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",url:"http://www.ourgames.ru/igra/chempion-po-plavaniiu"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-1/200X120_170521_1503068454.png",url:"http://www.ourgames.ru/igra/master-shashek"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-1-9/200X120_170519_1503065531.png",url:"http://www.ourgames.ru/igra/blok-domino"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-4-1/200X120_170541_1503321513.png",
url:"http://www.ourgames.ru/igra/classic-backgammon-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",url:"http://www.ourgames.ru/igra/mir-svobodnykh-slov"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",url:"http://www.ourgames.ru/igra/pazl-deliuks"});break;case "oyungemisi.com":a.push({img:"http://static.oyungemisi.com/games/assets/icons/3/112243/89539/96x96-380646.jpg?r=1502194273127",url:"http://oyungemisi.com/minigolf-world-oyun/"});
break;case "quicksave.su":a.push({img:"http://st.manamonster.com/images/games/1/11945-jigsaw-deluxe-300x169.jpg",url:"http://quicksave.su/games/11945-jigsaw-deluxe"});break;case "raketka.cz":a.push({img:"http://www.raketka.cz/gamedata/images/27865_172_152.png",url:"http://www.raketka.cz/h/neon-pong"});a.push({img:"http://www.raketka.cz/gamedata/images/27862_172_152.png",url:"http://www.raketka.cz/h/nine-mens-morris"});break;case "silvergames.com":a.push({img:"http://i1.silvergames.com/p/b/minigolf-world.png",
url:"http://www.silvergames.com/en/minigolf-world"});a.push({img:"http://i2.silvergames.com/p/a/snake-and-blocks.png",url:"http://www.silvergames.com/en/snake-and-blocks"});break;case "spela.se":a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",url:"http://www.spela.se/spel_/lanka-ihop-4-klassisk"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",url:"http://www.spela.se/spel_/orm-och-block"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",
url:"http://www.spela.se/spel_/simmarproffs"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-1/200X120_170521_1503068454.png",url:"http://www.spela.se/spel_/damspelmastare"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-1-9/200X120_170519_1503065531.png",url:"http://www.spela.se/spel_/dominoblock"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-4-1/200X120_170541_1503321513.png",url:"http://www.spela.se/spel_/classic-backgammon-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",
url:"http://www.spela.se/spel_/gratis-ord"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",url:"http://www.spela.se/spel_/pussel-med-vilda-djur"});break;case "spele.be":a.push({img:"http://static.spele.be/games/assets/screenshots/3/112243/89539/222x140-380645.jpg",url:"http://spele.be/minigolf-world-spel/"});a.push({img:"http://static.spele.be/games/assets/screenshots/9/68979/41390/222x140-85104.jpg",url:"http://spele.be/connect-4-spel/"});break;case "spele.nl":a.push({img:"http://spele.nl/minigolf-world-spel/",
url:"http://spele.nl/connect-4-spel/"});a.push({img:"http://static.spele.nl/games/assets/icons/3/112243/89539/96x96-380646.jpg",url:"http://spele.nl/minigolf-world-spel/"});break;case "spelletjes.nl":a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",url:"http://www.spelletjes.nl/spel/slang-en-blokken"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",url:"http://www.spelletjes.nl/spel/klassieke-4-op-een-rij"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",
url:"http://www.spelletjes.nl/spel/zwemkampioen"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-1/200X120_170521_1503068454.png",url:"http://www.spelletjes.nl/spel/dammeester"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-1-9/200X120_170519_1503065531.png",url:"http://www.spelletjes.nl/spel/dominostenen"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-4-1/200X120_170541_1503321513.png",url:"http://www.spelletjes.nl/spel/classic-backgammon-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",
url:"http://www.spelletjes.nl/spel/woorden-vormen"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",url:"http://www.spelletjes.nl/spel/puzzel-deluxe"});break;case "spielen.es":a.push({img:"http://i2.spielen.es/p/a/minigolf-world.png",url:"http://www.spielen.es/de/minigolf-world"});a.push({img:"http://i2.spielen.es/p/a/snake-and-blocks.png",url:"http://www.spielen.es/de/snake-and-blocks"});break;case "spielen.com":a.push({img:"http://files.cdn.spilcloud.com/thumbs-7-2/200X120_170472_1502697306.png",
url:"http://www.spielen.com/spiel/vier-gewinnt-klassisch"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-6-0/200X120_170460_1502450874.png",url:"http://www.spielen.com/spiel/schlange-und-blocke"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-7/200X120_165627.jpg",url:"http://www.spielen.com/spiel/swimming-pro"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-1/200X120_170521_1503068454.png",url:"http://www.spielen.com/spiel/meister-in-dame"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-1-9/200X120_170519_1503065531.png",
url:"http://www.spielen.com/spiel/domino-block"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-4-1/200X120_170541_1503321513.png",url:"http://www.spielen.com/spiel/classic-backgammon-"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-2/200X120_170522_1503302595.png",url:"http://www.spielen.com/spiel/freie-worter"});a.push({img:"http://files.cdn.spilcloud.com/thumbs-2-0/200X120_170520_1503067878.png",url:"http://www.spielen.com/spiel/puzzle-deluxe"});break;case "spielert.de":a.push({img:"http://spielert.de/uploads/thumbs/nine-men-s-morris-online-mills-game.jpg",
url:"http://spielert.de/denk/Nine-Men-s-Morris-Online-Mills-Game"});break;case "superhry.cz":a.push({img:"http://data6.superhry.cz/cnt_img/014/14758_340.jpg",url:"http://www.superhry.cz/hra/14758-gear-madness"});break;case "yo-yoo.co.il":a.push({img:"http://www.yo-yoo.co.il/uploads/chesssonline.jpg",url:"http://games.yo-yoo.co.il/games_play.php?game=5139"});a.push({img:"http://www.yo-yoo.co.il/uploads/4ineorafa.png",url:"http://games.yo-yoo.co.il/games_play.php?game=5140"});a.push({img:"http://www.yo-yoo.co.il/uploads/sheshshsobae.jpg",
url:"http://games.yo-yoo.co.il/games_play.php?game=5147"});break;case "zebest-3000.com":a.push({img:"http://cdn.zebest-3000.com/img/general/games/200x150/23088.jpg",url:"http://www.zebest-3000.com/jeux/jeu-23088.html"})}return a}var s_iScaleFactor=1,s_bIsIphone=!1,s_iOffsetX,s_iOffsetY;
(function(b){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(b)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(b.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(b){console.log(b)}
function getSize(b){var a=b.toLowerCase(),c=window.document,e=c.documentElement;if(void 0===window["inner"+b])b=e["client"+b];else if(window["inner"+b]!=e["client"+b]){var f=c.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var d=c.createElement("div");d.id="vpw-test-d";d.style.cssText="position:absolute;top:-1000px";d.innerHTML="<style>@media("+a+":"+e["client"+b]+"px){body#vpw-test-b div#vpw-test-d{"+a+":7px!important}}</style>";f.appendChild(d);e.insertBefore(f,c.head);
b=7==d["offset"+b]?e["client"+b]:window["inner"+b];e.removeChild(f)}else b=window["inner"+b];return b}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}
function isIOS(){var b="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");for(-1!==navigator.userAgent.toLowerCase().indexOf("iphone")&&(s_bIsIphone=!0);b.length;)if(navigator.platform===b.pop())return!0;return s_bIsIphone=!1}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var b=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<b?b:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var b=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var a=getSize("Width");_checkOrientation(a,b);var c=Math.min(b/CANVAS_HEIGHT,a/CANVAS_WIDTH),e=CANVAS_WIDTH*c;c*=CANVAS_HEIGHT;if(c<b){var f=b-c;c+=f;e+=CANVAS_WIDTH/CANVAS_HEIGHT*f}else e<a&&(f=a-e,e+=f,c+=CANVAS_HEIGHT/CANVAS_WIDTH*f);f=b/2-c/2;var d=a/2-e/2,k=CANVAS_WIDTH/e;if(d*k<-EDGEBOARD_X||f*k<-EDGEBOARD_Y)c=Math.min(b/(CANVAS_HEIGHT-2*
EDGEBOARD_Y),a/(CANVAS_WIDTH-2*EDGEBOARD_X)),e=CANVAS_WIDTH*c,c*=CANVAS_HEIGHT,f=(b-c)/2,d=(a-e)/2,k=CANVAS_WIDTH/e;s_iOffsetX=-1*d*k;s_iOffsetY=-1*f*k;0<=f&&(s_iOffsetY=0);0<=d&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos();null!==s_oMenu&&s_oMenu.refreshButtonPos();null!==s_oModePanel&&s_oModePanel.refreshButtonPos();s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*e,s_oStage.canvas.height=2*c,canvas.style.width=e+"px",canvas.style.height=c+"px",
s_oStage.scaleX=s_oStage.scaleY=2*Math.min(e/CANVAS_WIDTH,c/CANVAS_HEIGHT)):s_bMobile||isChrome()?($("#canvas").css("width",e+"px"),$("#canvas").css("height",c+"px")):(s_oStage.canvas.width=e,s_oStage.canvas.height=c,s_iScaleFactor=Math.min(e/CANVAS_WIDTH,c/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>f?$("#canvas").css("top",f+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",d+"px")}}
function _checkOrientation(b,a){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(b>a?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(b){return!0}}function playSound(b,a,c){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[b].play(),s_aSounds[b].volume(a),s_aSounds[b].loop(c),s_aSounds[b]):null}function stopSound(b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[b].stop()}function setVolume(b,a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[b].volume(a)}
function setMute(b,a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[b].mute(a)}function fadeVolume(b,a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(new createjs.Tween.get(b)).to({volume:a},c)}function createBitmap(b,a,c){var e=new createjs.Bitmap(b),f=new createjs.Shape;a&&c?f.graphics.beginFill("#fff").drawRect(0,0,a,c):f.graphics.beginFill("#ff0").drawRect(0,0,b.width,b.height);e.hitArea=f;return e}
function createSprite(b,a,c,e,f,d){b=null!==a?new createjs.Sprite(b,a):new createjs.Sprite(b);a=new createjs.Shape;a.graphics.beginFill("#000000").drawRect(-c,-e,f,d);b.hitArea=a;return b}function randomFloatBetween(b,a,c){"undefined"===typeof c&&(c=2);return parseFloat(Math.min(b+Math.random()*(a-b),a).toFixed(c))}function rotateVector2D(b,a){var c=a.getX()*Math.cos(b)+a.getY()*Math.sin(b),e=a.getX()*-Math.sin(b)+a.getY()*Math.cos(b);a.set(c,e)}function tweenVectorsOnX(b,a,c){return b+c*(a-b)}
function shuffle(b){for(var a=b.length,c,e;0!==a;)e=Math.floor(Math.random()*a),--a,c=b[a],b[a]=b[e],b[e]=c;return b}function bubbleSort(b){do{var a=!1;for(var c=0;c<b.length-1;c++)b[c]>b[c+1]&&(a=b[c],b[c]=b[c+1],b[c+1]=a,a=!0)}while(a)}function compare(b,a){return b.index>a.index?-1:b.index<a.index?1:0}function easeLinear(b,a,c,e){return c*b/e+a}function easeInQuad(b,a,c,e){return c*(b/=e)*b+a}function easeInSine(b,a,c,e){return-c*Math.cos(b/e*(Math.PI/2))+c+a}
function easeInCubic(b,a,c,e){return c*(b/=e)*b*b+a}function getTrajectoryPoint(b,a){var c=new createjs.Point,e=(1-b)*(1-b),f=b*b;c.x=e*a.start.x+2*(1-b)*b*a.traj.x+f*a.end.x;c.y=e*a.start.y+2*(1-b)*b*a.traj.y+f*a.end.y;return c}function formatTime(b){b/=1E3;var a=Math.floor(b/60);b=Math.floor(b-60*a);var c="";c=10>a?c+("0"+a+":"):c+(a+":");return 10>b?c+("0"+b):c+b}function degreesToRadians(b){return b*Math.PI/180}function distance(b,a){return Math.sqrt((a.x-b.x)*(a.x-b.x)+(a.y-b.y)*(a.y-b.y))}
function distance2(b,a){return(a.x-b.x)*(a.x-b.x)+(a.y-b.y)*(a.y-b.y)}function NoClickDelay(b){this.element=b;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(b){for(var a=b.length,c,e;0<a;)e=Math.floor(Math.random()*a),a--,c=b[a],b[a]=b[e],b[e]=c;return b}
NoClickDelay.prototype={handleEvent:function(b){switch(b.type){case "touchstart":this.onTouchStart(b);break;case "touchmove":this.onTouchMove(b);break;case "touchend":this.onTouchEnd(b)}},onTouchStart:function(b){b.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(b){this.moved=!0},onTouchEnd:function(b){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){b=document.elementFromPoint(b.changedTouches[0].clientX,b.changedTouches[0].clientY);3==b.nodeType&&(b=b.parentNode);var a=document.createEvent("MouseEvents");a.initEvent("click",!0,!0);b.dispatchEvent(a)}}};
(function(){function b(b){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};b=b||window.event;b.type in c?document.body.className=c[b.type]:(document.body.className=this[a]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var a="hidden";a in document?document.addEventListener("visibilitychange",b):(a="mozHidden")in document?document.addEventListener("mozvisibilitychange",b):(a="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",b):(a="msHidden")in document?document.addEventListener("msvisibilitychange",b):"onfocusin"in document?document.onfocusin=document.onfocusout=b:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=b})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(b){for(var a=window.location.search.substring(1).split("&"),c=0;c<a.length;c++){var e=a[c].split("=");if(e[0]==b)return e[1]}}window.GD_OPTIONS={gameId:"d7b10d9e32844525a0bfa1fef7324895",onEvent:function(b){switch(b.name){case "SDK_GAME_START":s_oMain.startUpdate();break;case "SDK_GAME_PAUSE":s_oMain.stopUpdate()}}};
(function(b,a,c){var e=b.getElementsByTagName(a)[0];b.getElementById(c)||(b=b.createElement(a),b.id=c,b.src="https://html5.api.gamedistribution.com/main.min.js",e.parentNode.insertBefore(b,e))})(document,"script","gamedistribution-jssdk");
function CSpriteLibrary(){var b,a,c,e,f,d;this.init=function(k,h,l){c=a=0;e=k;f=h;d=l;b={}};this.addSprite=function(f,d){b.hasOwnProperty(f)||(b[f]={szPath:d,oSprite:new Image},a++)};this.getSprite=function(a){return b.hasOwnProperty(a)?b[a].oSprite:null};this._onSpritesLoaded=function(){f.call(d)};this._onSpriteLoaded=function(){e.call(d);++c==a&&this._onSpritesLoaded()};this.loadSprites=function(){for(var a in b)b[a].oSprite.oSpriteLibrary=this,b[a].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
b[a].oSprite.src=b[a].szPath};this.getNumSprites=function(){return a}}
var CANVAS_WIDTH=1700,CANVAS_HEIGHT=768,EDGEBOARD_X=300,EDGEBOARD_Y=0,FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="comfortaa",STATE_LOADING=0,STATE_MENU=1,STATE_CHOOSE_MODE=2,STATE_HELP=3,STATE_GAME=4,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_RELEASE_YES=6,ON_RELEASE_NO=7,MODE_CPU=0,MODE_HUMAN=1,BOARD_ROWS=6,BOARD_COLS=7,DISC_YELLOW=0,DISC_RED=1,DISC_EMPTY=2,DISC_GENERIC=3,DISC_RADIUS=39,DISC_DIAMETER=2*DISC_RADIUS,DISC_FOR_COMBOS=
4,TIME_FOR_DROP_PER_CELL=200,POINTS_FOR_WIN,TIME_FOR_BONUS_SCORE,TIME_WIN_DISC=1E3,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION,TEXT_SCORE="TOTAL SCORE",TEXT_BONUS_TIME="BONUS TIME",TEXT_BONUS_WIN="BONUS WIN",TEXT_YOU_LOSE="YOU LOSE",TEXT_CONGRATS="CONGRATULATIONS",TEXT_RED_WINS="RED WINS",TEXT_YELLOW_WINS="YELLOW WINS",TEXT_PLAYER_TURN="PLAYER TURN",TEXT_CPU_TURN="CPU TURN",TEXT_PLAYER1_TURN="PLAYER 1 TURN",TEXT_PLAYER2_TURN="PLAYER 2 TURN",TEXT_TIE="IT'S A TIE!!",TEXT_CHOOSE_MODE="CHOOSE GAME MODE",
TEXT_ARE_YOU_SURE="ARE YOU SURE?",TEXT_DEVELOPED="developed by",TEXT_SHARE_IMAGE="200x200.jpg",TEXT_SHARE_TITLE="Congratulations!",TEXT_SHARE_MSG1="You collected <strong>",TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!",TEXT_SHARE_SHARE1="My score is ",TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var b,a,c,e;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress","./sprites/progress.png");s_oSpriteLibrary.loadSprites();e=new createjs.Container;s_oStage.addChild(e)};this.unload=function(){createjs.Tween.removeTweens(a);e.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(c).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var f=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));e.addChild(f);f=s_oSpriteLibrary.getSprite("progress");a=createBitmap(f);a.regX=f.width/2;a.regY=f.height/2;a.x=CANVAS_WIDTH/2+270;a.y=CANVAS_HEIGHT/2+100;e.addChild(a);b=new createjs.Text("","100px "+PRIMARY_FONT,"#008df0");b.x=CANVAS_WIDTH/2+280;b.y=CANVAS_HEIGHT/2+150;
b.textBaseline="alphabetic";b.textAlign="center";e.addChild(b);c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=0;e.addChild(c);createjs.Tween.get(a,{loop:!0}).to({rotation:360},1E3)};this.refreshLoader=function(a){b.text=a+"%"};this._init()}
function CMain(b){var a,c=0,e=0,f=STATE_LOADING,d,k;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(FPS);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;d=new CPreloader};this.preloaderReady=function(){s_oMain._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_oMain._initSounds()};this.soundLoaded=function(){c++;d.refreshLoader(Math.floor(c/e*100));c===e&&this._allResourcesLoaded()};this._initSounds=function(){var a=[];a.push({path:"./sounds/",filename:"win",loop:!1,volume:1,ingamename:"win"});a.push({path:"./sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});a.push({path:"./sounds/",
filename:"game_over",loop:!1,volume:1,ingamename:"game_over"});a.push({path:"./sounds/",filename:"drop",loop:!1,volume:1,ingamename:"drop"});a.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});e+=a.length;s_aSounds=[];for(var b=0;b<a.length;b++)s_aSounds[a[b].ingamename]=new Howl({src:[a[b].path+a[b].filename+".mp3",a[b].path+a[b].filename+".ogg"],autoplay:!1,preload:!0,loop:a[b].loop,volume:a[b].volume,onload:s_oMain.soundLoaded()})};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,
this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("ctl_logo","./sprites/ctl_logo.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("bg_selection","./sprites/bg_selection.jpg");s_oSpriteLibrary.addSprite("but_exit",
"./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("but_no","./sprites/but_no.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("but_cpu","./sprites/but_cpu.png");s_oSpriteLibrary.addSprite("but_human","./sprites/but_human.png");s_oSpriteLibrary.addSprite("but_restart",
"./sprites/but_restart.png");s_oSpriteLibrary.addSprite("board_back","./sprites/board_back.png");s_oSpriteLibrary.addSprite("board_front","./sprites/board_front.png");s_oSpriteLibrary.addSprite("disc","./sprites/disc.png");s_oSpriteLibrary.addSprite("bg_turn","./sprites/bg_turn.png");s_oSpriteLibrary.addSprite("arrow","./sprites/arrow.png");s_oSpriteLibrary.addSprite("time_icon","./sprites/time_icon.png");s_oSpriteLibrary.addSprite("win_effect","./sprites/win_effect.png");e+=s_oSpriteLibrary.getNumSprites();
s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){c++;d.refreshLoader(Math.floor(c/e*100));c===e&&this._allResourcesLoaded()};this._allResourcesLoaded=function(){d.unload();isIOS()||(s_oSoundTrack=playSound("soundtrack",1,!0));s_oMain.gotoMenu()};this._onAllImagesLoaded=function(){};this.gotoMenu=function(){new CMenu;f=STATE_MENU;showMoreGames()};this.gotoModePanel=function(){new CModePanel;f=STATE_CHOOSE_MODE};this.gotoGame=function(){k=new CGame(h);f=STATE_GAME;hideMoreGames()};this.gotoHelp=
function(){new CHelp;f=STATE_HELP};this.selectMode=function(a){s_iCurMode=a;this.gotoGame()};this.stopUpdate=function(){a=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();a=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(b){if(!1!==a){var d=
(new Date).getTime();s_iTimeElaps=d-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=d;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&k.update();s_oStage.update(b)}};s_oMain=this;var h=b;ENABLE_FULLSCREEN=b.fullscreen;ENABLE_CHECK_ORIENTATION=b.check_orientation;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oStage,s_oMain,s_oSpriteLibrary,s_oCanvas,s_bFullscreen=!1,s_iCurMode,s_oSoundTrack=null,s_iPrevTurn=-1,s_aSounds;
function CTextButton(b,a,c,e,f,d,k){var h,l,g,n,m;this._init=function(a,b,d,f,c,e,k){h=[];l=[];var p=createBitmap(d),y=Math.ceil(k/20);m=new createjs.Text(f," "+k+"px "+c,"#000000");m.textAlign="center";m.textBaseline="alphabetic";var v=m.getBounds();m.x=d.width/2+y;m.y=Math.floor(d.height/2)+v.height/3+y;n=new createjs.Text(f," "+k+"px "+c,e);n.textAlign="center";n.textBaseline="alphabetic";v=n.getBounds();n.x=d.width/2;n.y=Math.floor(d.height/2)+v.height/3-9;g=new createjs.Container;g.x=a;g.y=b;
g.regX=d.width/2;g.regY=d.height/2;g.addChild(p,m,n);s_oStage.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown");g.off("pressup");s_bMobile||g.off("mouseover",this.buttonOver);s_oStage.removeChild(g)};this.setVisible=function(a){g.visible=a};this._initListener=function(){oParent=this;g.on("mousedown",this.buttonDown);g.on("pressup",this.buttonRelease);if(!s_bMobile)g.on("mouseover",this.buttonOver)};this.addEventListener=function(a,b,d){h[a]=b;l[a]=d};this.buttonRelease=function(){g.scaleX=
1;g.scaleY=1;h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(l[ON_MOUSE_UP])};this.buttonDown=function(){g.scaleX=.9;g.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};this.buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.setNoShadow=function(){g.removeChild(m)};this.setTextPosition=function(a){n.y=a;m.y=a+2};this.setPosition=function(a,b){g.x=a;g.y=b};this.setX=function(a){g.x=a};this.setY=function(a){g.y=a};this.getButtonImage=function(){return g};this.getX=function(){return g.x};
this.getY=function(){return g.y};this._init(b,a,c,e,f,d,k);return this}
function CToggle(b,a,c,e,f){var d,k,h,l;this._init=function(a,b,f,c){k=[];h=[];var e=new createjs.SpriteSheet({images:[f],frames:{width:f.width/2,height:f.height,regX:f.width/2/2,regY:f.height/2},animations:{state_true:[0],state_false:[1]}});d=c;l=createSprite(e,"state_"+d,f.width/2/2,f.height/2,f.width/2,f.height);l.x=a;l.y=b;l.stop();g.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown",this.buttonDown);l.off("pressup",this.buttonRelease);s_bMobile||l.off("mouseover",this.buttonOver);
g.removeChild(l)};this._initListener=function(){l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease);if(!s_bMobile)l.on("mouseover",this.buttonOver)};this.addEventListener=function(a,b,d){k[a]=b;h[a]=d};this.setActive=function(a){d=a;l.gotoAndStop("state_"+d)};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;playSound("click",1,0);d=!d;l.gotoAndStop("state_"+d);k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(h[ON_MOUSE_UP],d)};this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;k[ON_MOUSE_DOWN]&&
k[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.setPosition=function(a,b){l.x=a;l.y=b};var g=f;this._init(b,a,c,e)}
function CGfxButton(b,a,c,e){var f,d,k,h,l,g;this._init=function(a,b,c,e){f=!1;d=1;h=[];l=[];g=createBitmap(c);g.x=a;g.y=b;g.scaleX=g.scaleY=d;g.regX=c.width/2;g.regY=c.height/2;e.addChild(g);this._initListener()};this.unload=function(){s_bMobile?g.off("mousedown",this.buttonDown):(g.off("mousedown",this.buttonDown),g.off("mouseover",this.buttonOver));g.off("pressup",this.buttonRelease);e.removeChild(g)};this.setVisible=function(a){g.visible=a};this.enable=function(){f=!0};this.disable=function(){f=
!1};this._initListener=function(){if(s_bMobile)g.on("mousedown",this.buttonDown);else g.on("mousedown",this.buttonDown),g.on("mouseover",this.buttonOver);g.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){h[a]=b;l[a]=d};this.addEventListenerWithParams=function(a,b,d,f){h[a]=b;l[a]=d;k=f};this.buttonRelease=function(){f||(g.scaleX=d,g.scaleY=d,h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(l[ON_MOUSE_UP],k))};this.buttonDown=function(){f||(g.scaleX=.9*d,g.scaleY=.9*d,playSound("click",
1,0),h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN],k))};this.buttonOver=function(a){s_bMobile||f||(a.target.cursor="pointer")};this.inversePulse=function(){createjs.Tween.get(g).to({scaleX:1.1*d,scaleY:1.1*d},1050,createjs.Ease.quadOut).to({scaleX:d,scaleY:d},850,createjs.Ease.quadIn).call(function(){n.inversePulse()})};this.pulseAnimation=function(){createjs.Tween.get(g).to({scaleX:.9*d,scaleY:.9*d},850,createjs.Ease.quadOut).to({scaleX:d,scaleY:d},650,createjs.Ease.quadIn).call(function(){n.pulseAnimation()})};
this.trembleAnimation=function(){createjs.Tween.get(g).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){n.trebleAnimation()})};this.setPosition=function(a,b){g.x=a;g.y=b};this.setX=function(a){g.x=a};this.setY=function(a){g.y=a};this.getButtonImage=function(){return g};this.getX=function(){return g.x};this.getY=function(){return g.y};var n=this;this._init(b,a,c,e);return this}
function CMenu(){var b,a,c,e,f,d,k,h,l,g,n,m,p=null,t=null;this._init=function(){k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(k);var q=s_oSpriteLibrary.getSprite("but_play");h=new CGfxButton(CANVAS_WIDTH/2+280,CANVAS_HEIGHT/2+160,q,s_oStage);h.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);h.inversePulse();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q=s_oSpriteLibrary.getSprite("audio_icon"),f=CANVAS_WIDTH-q.height/2-10,d=q.height/2+10,g=new CToggle(f,d,q,s_bAudioActive,
s_oStage),g.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);q=s_oSpriteLibrary.getSprite("but_credits");c=q.height/2+10;e=q.height/2+10;n=new CGfxButton(c,e,q,s_oStage);n.addEventListener(ON_MOUSE_UP,this._onButCreditRelease,this);q=window.document;var u=q.documentElement;p=u.requestFullscreen||u.mozRequestFullScreen||u.webkitRequestFullScreen||u.msRequestFullscreen;t=q.exitFullscreen||q.mozCancelFullScreen||q.webkitExitFullscreen||q.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(p=!1);p&&!1===
inIframe()&&(q=s_oSpriteLibrary.getSprite("but_fullscreen"),b=c+q.width/2+10,a=e,m=new CToggle(b,a,q,s_bFullscreen,s_oStage),m.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));l=new createjs.Shape;l.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(l);createjs.Tween.get(l).to({alpha:0},1E3).call(function(){l.visible=!1});this.refreshButtonPos()};this.unload=function(){h.unload();h=null;n.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)g.unload(),
g=null;p&&!1===inIframe()&&m.unload();s_oStage.removeAllChildren();s_oMenu=k=null};this.refreshButtonPos=function(){n.setPosition(c+s_iOffsetX,s_iOffsetY+e);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||g.setPosition(f-s_iOffsetX,s_iOffsetY+d);p&&!1===inIframe()&&m.setPosition(b+s_iOffsetX,a+s_iOffsetY)};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){gdsdk.showBanner();this.unload();isIOS()&&null===s_oSoundTrack&&(s_oSoundTrack=
playSound("soundtrack",1,!0));$(s_oMain).trigger("start_session");s_oMain.gotoModePanel()};this._onButCreditRelease=function(){new CCreditsPanel};this._onFullscreenRelease=function(){s_bFullscreen?(t.call(window.document),s_bFullscreen=!1):(p.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(b){var a=!1,c,e,f,d,k,h,l,g,n=null;this._init=function(){d=DISC_RED;var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);h=new createjs.Container;s_oStage.addChild(h);l=new CBoard(473,103,h);g=new CInterface;n=new CEndPanel;s_iCurMode===MODE_CPU&&(k=new CAIController,k.setEnemyCode(d));this.reset()};this.unload=function(){g.unload();n.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren();s_oGame=null};this.reset=function(){e=0;s_iPrevTurn=
c=-1===s_iPrevTurn?Math.round(Math.random()):1-s_iPrevTurn;f=0;d!==c&&s_iCurMode===MODE_CPU&&(l.blockHitArea(),k.throwCoin(l.getLogicBoard()));this.refreshTurn();g.enableGUI(!1);setVolume("soundtrack",.3);a=!0};this.restart=function(){l.reset();this.reset();this.refreshTurn()};this.setUpdate=function(b){a=b};this.changeTurn=function(){c=1-c;this.refreshTurn();c!==d&&s_iCurMode===MODE_CPU?k.throwCoin(l.getLogicBoard()):l.playerTurn(!1)};this.refreshTurn=function(){g.refreshTurn(c,s_iCurMode===MODE_CPU?
c===d?TEXT_PLAYER_TURN:TEXT_CPU_TURN:0===c?TEXT_PLAYER1_TURN:TEXT_PLAYER2_TURN)};this.checkCombos=function(){l.checkWinCombo(c)?(l.playWinAnim(),setTimeout(function(){s_oGame.endOfMatch()},2*TIME_WIN_DISC)):this.changeTurn()};this.endOfMatch=function(){a=!1;g.enableGUI(!1);var b=0;c===d&&(b=TIME_FOR_BONUS_SCORE-e,0>b&&(b=0));n.show(c,d,b)};this.dropDisc=function(a){s_iCurMode===MODE_CPU&&k.setLastEnemyThrowCol(a)};this.dropDiscByCpu=function(a){l.dropDiscByCpu(a,c)};this.disableColumn=function(){f++;
f===BOARD_COLS&&new CTiePanel};this.getCurTurn=function(){return c};this.onExit=function(){this.unload();s_oMain.gotoMenu()};this.update=function(){a&&(e+=s_iTimeElaps,g.refreshTime(formatTime(e)))};s_oGame=this;TIME_FOR_BONUS_SCORE=1E3*b.bonus_time;POINTS_FOR_WIN=b.points_for_win;this._init()}var s_oGame;
function CInterface(){var b,a,c,e,f,d,k,h,l,g,n,m,p,t,q,u=null,x=null;this._init=function(){var r=s_oSpriteLibrary.getSprite("but_exit");k=CANVAS_WIDTH-r.width/2-10;h=r.height/2+10;g=new CGfxButton(k,h,r,s_oStage);g.addEventListener(ON_MOUSE_UP,this._onExit,this);r=s_oSpriteLibrary.getSprite("but_restart");b=k-r.width-10;a=h;n=new CGfxButton(b,a,r,s_oStage);n.addEventListener(ON_MOUSE_UP,this._onRestartRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f=b-r.width-10,d=a,l=new CToggle(f,d,
s_oSpriteLibrary.getSprite("audio_icon"),s_bAudioActive,s_oStage),l.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);r=window.document;var w=r.documentElement;u=w.requestFullscreen||w.mozRequestFullScreen||w.webkitRequestFullScreen||w.msRequestFullscreen;x=r.exitFullscreen||r.mozCancelFullScreen||r.webkitExitFullscreen||r.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(u=!1);u&&!1===inIframe()&&(r=s_oSpriteLibrary.getSprite("but_fullscreen"),c=r.width/4+10,e=r.height/2+4,m=new CToggle(c,e,r,s_bFullscreen,
s_oStage),m.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));r=createBitmap(s_oSpriteLibrary.getSprite("time_icon"));r.x=CANVAS_WIDTH/2-120;r.y=700;s_oStage.addChild(r);p=new createjs.Text("00:00","50px "+PRIMARY_FONT,"#007eff");p.x=CANVAS_WIDTH/2;p.y=750;p.textAlign="center";p.textBaseline="alphabetic";p.lineWidth=200;s_oStage.addChild(p);t=new CTurnPanel(1240,510,s_oStage);q=new CAreYouSurePanel(s_oStage);this.refreshButtonPos()};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||
!1===s_bMobile)l.unload(),l=null;u&&!1===inIframe()&&m.unload();g.unload();n.unload()};this.refreshButtonPos=function(){g.setPosition(k-s_iOffsetX,s_iOffsetY+h);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||l.setPosition(f-s_iOffsetX,s_iOffsetY+d);u&&!1===inIframe()&&m.setPosition(c+s_iOffsetX,e+s_iOffsetY);n.setPosition(b-s_iOffsetX,a+s_iOffsetY)};this.enableGUI=function(a){a?(g.enable(),n.enable()):(g.disable(),n.disable())};this.refreshTime=function(a){p.text=a};this.refreshTurn=function(a,b){t.setTurn(a,
b)};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.setUpdate(!1);q.show(TEXT_ARE_YOU_SURE);q.addEventListener(ON_RELEASE_YES,this._onReleaseYes);q.addEventListener(ON_RELEASE_NO,this._onReleaseNo)};this._onReleaseYes=function(){$(s_oMain).trigger("end_session");$(s_oMain).trigger("show_interlevel_ad");s_oGame.onExit()};this._onReleaseNo=function(){s_oGame.setUpdate(!0)};this._onRestartRelease=function(){s_oGame.restart()};
this._onFullscreenRelease=function(){s_bFullscreen?(x.call(window.document),s_bFullscreen=!1):(u.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CEndPanel(){var b,a,c,e,f,d,k,h,l;this._init=function(){a=new createjs.Container;a.visible=!1;b=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));l=b.on("click",function(){});a.addChild(b);c=new createjs.Text(""," 50px "+PRIMARY_FONT,"#fff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2-142;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=600;a.addChild(c);f=new createjs.Text(""," 30px "+PRIMARY_FONT,"#fff");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-60;f.textAlign="center";f.textBaseline=
"alphabetic";f.lineWidth=700;a.addChild(f);d=new createjs.Text(""," 30px "+PRIMARY_FONT,"#fff");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2-20;d.textAlign="center";d.textBaseline="alphabetic";d.lineWidth=700;a.addChild(d);e=new createjs.Text(""," 50px "+PRIMARY_FONT,"#fff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2+50;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=700;a.addChild(e);k=new CGfxButton(CANVAS_WIDTH/2-200,CANVAS_HEIGHT/2+120,s_oSpriteLibrary.getSprite("but_home"),a);k.addEventListener(ON_MOUSE_UP,
this._onButHome,this);h=new CGfxButton(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2+120,s_oSpriteLibrary.getSprite("but_restart"),a);h.addEventListener(ON_MOUSE_UP,this._onButRestart,this);s_oStage.addChild(a)};this.unload=function(){b.on("click",l);s_oStage.removeChild(a);k.unload();h.unload()};this.show=function(b,g,h){var k=0;s_iCurMode===MODE_HUMAN?(k+=POINTS_FOR_WIN,playSound("win",1,0),c.text=b===DISC_RED?TEXT_RED_WINS:TEXT_YELLOW_WINS):b===g?(playSound("win",1,0),k+=POINTS_FOR_WIN,c.text=TEXT_CONGRATS):
(playSound("game_over",1,0),c.text=TEXT_YOU_LOSE);f.text=TEXT_BONUS_TIME+": "+h;d.text=TEXT_BONUS_WIN+": "+k;b=h+k;e.text=TEXT_SCORE+" "+b;a.visible=!0;a.alpha=0;createjs.Tween.get(a).to({alpha:1},500,createjs.Ease.cubicOut).call(function(){});0<b&&($(s_oMain).trigger("save_score",b),$(s_oMain).trigger("share_event",void 0));setVolume("soundtrack",1)};this._onButHome=function(){$(s_oMain).trigger("show_interlevel_ad");g.unload();$(s_oMain).trigger("end_session");s_oGame.onExit()};this._onButRestart=
function(){$(s_oMain).trigger("show_interlevel_ad");a.visible=!1;s_oGame.restart()};var g=this;this._init();return this}
function CCreditsPanel(){var b,a,c,e,f;this._init=function(){b=new createjs.Container;s_oStage.addChild(b);var d=s_oSpriteLibrary.getSprite("msg_box");e=createBitmap(d);e.regX=d.width/2;e.regY=d.height/2;f=e.on("mousedown",this._onLogoButRelease);b.addChild(e);b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2;d=new createjs.Text(TEXT_DEVELOPED," 60px "+PRIMARY_FONT,"#ffffff");d.y=-90;d.textAlign="center";d.textBaseline="middle";d.lineWidth=600;b.addChild(d);d=new createjs.Text("www.codethislab.com"," 44px "+
PRIMARY_FONT,"#ffffff");d.y=80;d.textAlign="center";d.textBaseline="middle";d.lineWidth=600;b.addChild(d);d=s_oSpriteLibrary.getSprite("ctl_logo");c=createBitmap(d);c.regX=d.width/2;c.regY=d.height/2;b.addChild(c);d=s_oSpriteLibrary.getSprite("but_exit");a=new CGfxButton(276,-210,d,b);a.addEventListener(ON_MOUSE_UP,this.unload,this)};this.unload=function(){s_oStage.removeChild(void 0);s_oStage.removeChild(b);a.unload();e.off("mousedown",f)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};
this._init()}
function CAreYouSurePanel(b){var a,c,e,f,d,k,h;this._init=function(){a=[];c=[];h=new createjs.Container;k=h.on("click",function(){});h.visible=!1;l.addChild(h);var b=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));h.addChild(b);e=new createjs.Text("","70px "+PRIMARY_FONT,"#fff");e.textAlign="center";e.textBaseline="alphabetic";e.x=CANVAS_WIDTH/2;e.y=260;e.lineWidth=460;e.lineHeight=96;h.addChild(e);f=new CGfxButton(CANVAS_WIDTH/2+175,484,s_oSpriteLibrary.getSprite("but_yes"),h);f.addEventListener(ON_MOUSE_UP,this._onReleaseYes,
this);d=new CGfxButton(CANVAS_WIDTH/2-175,484,s_oSpriteLibrary.getSprite("but_no"),h);d.addEventListener(ON_MOUSE_UP,this._onReleaseNo,this)};this.addEventListener=function(b,d,f){a[b]=d;c[b]=f};this.unload=function(){h.off("click",k);d.unload();f.unload()};this.show=function(a){e.text=a;h.visible=!0;h.alpha=0;createjs.Tween.get(h).to({alpha:1},500,createjs.Ease.cubicOut)};this.hide=function(){h.visible=!1};this._onReleaseYes=function(){a[ON_RELEASE_YES]&&a[ON_RELEASE_YES].call(c[ON_RELEASE_YES])};
this._onReleaseNo=function(){a[ON_RELEASE_NO]&&a[ON_RELEASE_NO].call(c[ON_RELEASE_NO]);h.visible=!1};var l=b;this._init(b)}
function CModePanel(){var b,a,c,e,f,d,k,h,l=null,g=null,n;this._init=function(){n=new createjs.Container;s_oStage.addChild(n);var m=createBitmap(s_oSpriteLibrary.getSprite("bg_selection"));n.addChild(m);m=new createjs.Text(TEXT_CHOOSE_MODE," 80px "+PRIMARY_FONT,"#007eff");m.x=CANVAS_WIDTH/2;m.y=122;m.textAlign="center";m.textBaseline="alphabetic";m.lineWidth=600;n.addChild(m);f=new CGfxButton(CANVAS_WIDTH/2-200,CANVAS_HEIGHT/2,s_oSpriteLibrary.getSprite("but_cpu"),n);f.addEventListener(ON_MOUSE_UP,
this._onChooseCpu,this);d=new CGfxButton(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2,s_oSpriteLibrary.getSprite("but_human"),n);d.addEventListener(ON_MOUSE_UP,this._onChooseHuman,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m=s_oSpriteLibrary.getSprite("audio_icon"),c=CANVAS_WIDTH-m.height/2-10,e=m.height/2+10,k=new CToggle(c,e,m,s_bAudioActive,s_oStage),k.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);m=window.document;var p=m.documentElement;l=p.requestFullscreen||p.mozRequestFullScreen||p.webkitRequestFullScreen||
p.msRequestFullscreen;g=m.exitFullscreen||m.mozCancelFullScreen||m.webkitExitFullscreen||m.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(l=!1);l&&!1===inIframe()&&(m=s_oSpriteLibrary.getSprite("but_fullscreen"),b=m.height/2+10,a=m.height/2+10,h=new CToggle(b,a,m,s_bFullscreen,s_oStage),h.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));var t=new createjs.Shape;t.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);n.addChild(t);createjs.Tween.get(t).to({alpha:0},1E3).call(function(){t.visible=
!1});this.refreshButtonPos()};this.refreshButtonPos=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||k.setPosition(c-s_iOffsetX,s_iOffsetY+e);l&&!1===inIframe()&&h.setPosition(b+s_iOffsetX,a+s_iOffsetY)};this.unload=function(){f.unload();d.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k.unload(),k=null;l&&!1===inIframe()&&h.unload();s_oStage.removeAllChildren();s_oModePanel=null};this._onChooseCpu=function(){s_oModePanel.unload();s_oMain.selectMode(MODE_CPU)};this._onChooseHuman=function(){s_oModePanel.unload();
s_oMain.selectMode(MODE_HUMAN)};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onFullscreenRelease=function(){s_bFullscreen?(g.call(window.document),s_bFullscreen=!1):(l.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oModePanel=this;this._init()}var s_oModePanel=null;
function CBoard(b,a,c){var e,f,d,k,h,l,g,n,m,p,t,q,u;this._init=function(a,b){e=!1;u=new createjs.Container;u.x=a;u.y=b;r.addChild(u);var c=createBitmap(s_oSpriteLibrary.getSprite("board_back"));c.x=32;c.y=4;u.addChild(c);q=new createjs.Container;u.addChild(q);c=createBitmap(s_oSpriteLibrary.getSprite("board_front"));u.addChild(c);f=[];d=[];p=[];c=113;for(var v=531,m=0;m<BOARD_ROWS;m++){f[m]=[];d[m]=[];p[m]=[];for(var w=0;w<BOARD_COLS;w++)f[m][w]=DISC_EMPTY,d[m][w]={x:c,y:v},p[m][w]=null,c+=92;c=
113;v-=91.5}l=[];k=[];h=[];for(c=0;c<BOARD_COLS;c++)v=new createjs.Shape,v.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(d[d.length-1][c].x-DISC_RADIUS,d[d.length-1][c].y-DISC_RADIUS,DISC_DIAMETER,d[0][c].y+DISC_RADIUS),m=v.on("click",x.colSelected,null,!1,c),l.push({listener:m,event:"click"}),s_bMobile||(v.cursor="pointer",m=v.on("mouseover",x.colOver,null,!1,c),l.push({listener:m,event:"onmouseover"})),u.addChild(v),k[c]=v,h[c]={x:d[d.length-1][c].x,y:d[d.length-1][c].y-DISC_DIAMETER};c=s_oSpriteLibrary.getSprite("arrow");
t=createBitmap(c);t.regX=c.width/2;t.regY=c.height;t.x=h[0].x;t.y=h[0].y;t.visible=!1;u.addChild(t);g=[];g.push({row:2,col:0});g.push({row:1,col:0});g.push({row:0,col:0});g.push({row:0,col:1});g.push({row:0,col:2});g.push({row:0,col:3});n=[];n.push({row:2,col:6});n.push({row:1,col:6});n.push({row:0,col:6});n.push({row:0,col:5});n.push({row:0,col:4});n.push({row:0,col:3})};this.unload=function(){for(var a=0;a<l.length;a++)k[a].off(l[a].event,l[a].listener)};this.reset=function(){f=[];for(var a=0;a<
BOARD_ROWS;a++){f[a]=[];for(var b=0;b<BOARD_COLS;b++)f[a][b]=DISC_EMPTY,null!==p[a][b]&&(p[a][b].unload(),p[a][b]=null)}for(b=0;b<k.length;b++)k[b].visible=!0;e=!1};this.blockHitArea=function(){e=!0};this.playerTurn=function(a){e=a;t.visible=!0};this.colOver=function(a,b){e||(t.visible=!0);createjs.Tween.get(t).to({x:h[b].x},500,createjs.Ease.cubicOut)};this.colSelected=function(a,b){if(!e){e=!0;t.visible=!1;var c=x._findEmptyCellInColumns(b);f[c][b]=s_oGame.getCurTurn();var g=TIME_FOR_DROP_PER_CELL*
(BOARD_ROWS-c),l=new CDisc({x:h[b].x,y:h[b].y},s_oGame.getCurTurn(),q);l.drop(g,{x:d[c][b].x,y:d[c][b].y});p[c][b]=l;s_oGame.dropDisc(b);c===BOARD_ROWS-1&&(k[b].visible=!1,s_oGame.disableColumn())}};this.dropDiscByCpu=function(a,b){var d=this.getPointPerCol(a),f=d.end,c=d.row,e=TIME_FOR_DROP_PER_CELL*(BOARD_ROWS-c);d=new CDisc(d.start,b,q);d.drop(e,f);p[c][a]=d;c===BOARD_ROWS-1&&(k[a].visible=!1,s_oGame.disableColumn())};this._findEmptyCellInColumns=function(a){for(var b=0;b<BOARD_ROWS;b++)if(f[b][a]===
DISC_EMPTY)return b;return-1};this._checkHorizontalAdjacency=function(a,b){for(var d=0;d<BOARD_ROWS;d++){for(var c=[],e=0;e<BOARD_COLS;e++)if(0===c.length&&f[d][e]===a)c=[],c.push({row:d,col:e});else if(0<c.length&&f[d][e]!==a){if(c.length>=DISC_FOR_COMBOS)for(var g=0;g<c.length;g++)b.push(c[g]);c=[]}else 0<c.length&&f[d][e]===a&&c.push({row:d,col:e});if(c.length>=DISC_FOR_COMBOS)for(g=0;g<c.length;g++)b.push(c[g])}};this._checkVerticalAdjacency=function(a,b){for(var d=0;d<BOARD_COLS;d++){for(var c=
[],e=0;e<BOARD_ROWS;e++)if(0===c.length&&f[e][d]===a)c=[],c.push({row:e,col:d});else if(0<c.length&&f[e][d]!==a){if(c.length>=DISC_FOR_COMBOS)for(var g=0;g<c.length;g++)b.push(c[g]);c=[]}else 0<c.length&&f[e][d]===a&&c.push({row:e,col:d});if(c.length>=DISC_FOR_COMBOS)for(g=0;g<c.length;g++)b.push(c[g])}};this._checkDiagonalDxAdjacency=function(a,b){for(var d=0;d<g.length;d++){for(var c=[],e=0,h=0,k,l;g[d].row+e<BOARD_ROWS&&g[d].col+h<BOARD_COLS;){k=g[d].row+e;l=g[d].col+h;if(0===c.length&&f[k][l]===
a)c=[],c.push({row:k,col:l});else if(0<c.length&&f[k][l]!==a){if(c.length>=DISC_FOR_COMBOS)for(k=0;k<c.length;k++)b.push(c[k]);c=[]}else 0<c.length&&f[k][l]===a&&c.push({row:k,col:l});e++;h++}if(c.length>=DISC_FOR_COMBOS)for(k=0;k<c.length;k++)b.push(c[k])}};this._checkDiagonalSxAdjacency=function(a,b){for(var d=0;d<g.length;d++){for(var c=[],e=0,k=0,h,l;n[d].row+e<BOARD_ROWS&&-1<n[d].col+k;){h=n[d].row+e;l=n[d].col+k;if(0===c.length&&f[h][l]===a)c=[],c.push({row:h,col:l});else if(0<c.length&&f[h][l]!==
a){if(c.length>=DISC_FOR_COMBOS)for(h=0;h<c.length;h++)b.push(c[h]);c=[]}else 0<c.length&&f[h][l]===a&&c.push({row:h,col:l});e++;k--}if(c.length>=DISC_FOR_COMBOS)for(h=0;h<c.length;h++)b.push(c[h])}};this.checkWinCombo=function(a){m=[];this._checkHorizontalAdjacency(a,m);this._checkVerticalAdjacency(a,m);this._checkDiagonalDxAdjacency(a,m);this._checkDiagonalSxAdjacency(a,m);return 0<m.length?!0:!1};this.playWinAnim=function(){for(var a=0;a<m.length;a++)p[m[a].row][m[a].col].playWinAnim()};this.getLogicBoard=
function(){return f};this.getPointPerCol=function(a){var b=x._findEmptyCellInColumns(a);f[b][a]=s_oGame.getCurTurn();return{start:{x:h[a].x,y:h[a].y},end:{x:d[b][a].x,y:d[b][a].y},row:b}};var x=this;var r=c;this._init(b,a)}
function CDisc(b,a,c){var e,f,d;this._init=function(a,b){d=new createjs.Container;d.x=a.x;d.y=a.y;k.addChild(d);var c=s_oSpriteLibrary.getSprite("disc"),h={images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_0:[0],state_1:[1]}};h=new createjs.SpriteSheet(h);f=createSprite(h,"state_"+b,c.width/4/2,c.height/2,c.width/4,c.height);d.addChild(f);c=s_oSpriteLibrary.getSprite("win_effect");h={images:[c],frames:{width:78,height:78,regX:39,regY:39},animations:{stop:[0,
0],anim:[0,27]}};c=new createjs.SpriteSheet(h);e=createSprite(c,"stop",39,39,78,78);e.x=0;e.y=0;d.addChild(e)};this.unload=function(){k.removeChild(d)};this.drop=function(a,b){playSound("drop",1,0);createjs.Tween.get(d).to({y:b.y},a,createjs.Ease.bounceOut).call(function(){s_oGame.checkCombos()})};this.playWinAnim=function(){e.gotoAndPlay("anim")};this.setFrame=function(a){f.gotoAndStop("state_"+a)};var k=c;this._init(b,a)}
function CTurnPanel(b,a,c){var e,f,d;this._init=function(a,b){d=new createjs.Container;d.x=a;d.y=b;k.addChild(d);var c=s_oSpriteLibrary.getSprite("bg_turn"),h=createBitmap(c);d.addChild(h);f=new createjs.Text(s_iCurMode===MODE_CPU?TEXT_PLAYER_TURN:TEXT_PLAYER1_TURN,"20px "+PRIMARY_FONT,"#fff");f.x=c.width/2;f.y=36;f.textAlign="center";f.textBaseline="alphabetic";d.addChild(f);e=new CDisc({x:c.width/2,y:c.height/2+7},s_oGame.getCurTurn(),d)};this.setTurn=function(a,b){f.text=b;e.setFrame(a)};var k=
c;this._init(b,a)}
function CAIController(){var b,a,c,e;this._init=function(){a=b=DISC_GENERIC;c=[];c.push(3);c.push(4);c.push(2);c.push(5);c.push(1);c.push(6);c.push(0)};this.setLastEnemyThrowCol=function(a){};this.verifyIfPlayerWinsWithHorizontalLine=function(a,b,c,h,l){var d,f=0;var k=0;for(d=1;e[a][b+d]===c;)k++,d++;for(;e[a][b+d]===DISC_EMPTY;)d++,f++;for(d=-1;e[a][b+d]===c;)k++,d--;for(;e[a][b+d]===DISC_EMPTY;)d--,f++;l._iNumFreeAdiacency=f;return k>h?!0:!1};this.verifyIfPlayerWinsWithVerticalLine=function(a,
b,c,h){for(var d=0,f=-1;;)if(-1<a+f&&e[a+f][b]===c)d++,f--;else break;return d>h?!0:!1};this.verifyIfPlayerWinsWithDiagonalDxLine=function(a,b,c,h,l){for(var d=0,f=1,k=0;a+f<BOARD_ROWS&&e[a+f][b+f]===c;)d++,f++;for(;-1<b+f&&a+f<BOARD_ROWS&&e[a+f][b+f]===DISC_EMPTY;)f++,k++;for(f=-1;0<=a+f&&e[a+f][b+f]===c;)d++,f--;for(;0<=a+f&&0<=b+f&&e[a+f][b+f]===DISC_EMPTY;)f--,k++;l._iNumFreeAdiacency=k;return d>h?!0:!1};this.verifyIfPlayerWinsWithDiagonalSxLine=function(a,b,c,h,l){for(var d=0,f=1,k=0;0<=a-f&&
e[a-f][b+f]===c;)d++,f++;for(;0<=a-f&&b+f<BOARD_COLS&&e[a-f][b+f]===DISC_EMPTY;)k++,f++;for(f=1;a+f<BOARD_ROWS&&e[a+f][b-f]===c;)d++,f++;for(;-1<b-f&&a+f<BOARD_ROWS&&e[a+f][b-f]===DISC_EMPTY;)k++,f++;l._iNumFreeAdiacency=k;return d>h?!0:!1};this.verifyIfPlayerWins=function(a,b,c,e){var d={};return this.verifyIfPlayerWinsWithDiagonalDxLine(a,b,c,e,d)||this.verifyIfPlayerWinsWithDiagonalSxLine(a,b,c,e,d)||this.verifyIfPlayerWinsWithVerticalLine(a,b,c,e,d)||this.verifyIfPlayerWinsWithHorizontalLine(a,
b,c,e,d)?!0:!1};this.verifyProbablyPlayerColWinner=function(a,d){for(var f=[],h=0;h<BOARD_ROWS;h++)for(var l=0;l<BOARD_COLS;l++){var g=c[l];if(e[h][g]===DISC_EMPTY&&(0===h||null!==e[h-1][g]&&e[h-1][g]!==DISC_EMPTY)){var n={_iNumFreeAdiacency:0};this.verifyIfPlayerWinsWithDiagonalDxLine(h,g,a,d,n)&&2<n._iNumFreeAdiacency+d&&f.push(g);n._iNumFreeAdiacency=0;this.verifyIfPlayerWinsWithDiagonalSxLine(h,g,a,d,n)&&2<n._iNumFreeAdiacency+d&&f.push(g);n._iNumFreeAdiacency=0;this.verifyIfPlayerWinsWithHorizontalLine(h,
g,a,d,n)&&2<n._iNumFreeAdiacency+d&&f.push(g);a!==b&&this.verifyIfPlayerWinsWithVerticalLine(h,g,a,d)&&f.push(g)}}return f};this.verifyPlayerColWinner=function(a,b){for(var d=[],f=0;f<BOARD_ROWS;f++)for(var l=0;l<BOARD_COLS;l++){var g=c[l];e[f][g]===DISC_EMPTY&&(0==f||null!==e[f-1][g]&&e[f-1][g]!==DISC_EMPTY)&&this.verifyIfPlayerWins(f,g,a,b)&&d.push(g)}return d};this.setEnemyCode=function(c){b=c;a=c===DISC_RED?DISC_YELLOW:DISC_RED};this._getFreeRowFromCol=function(a){for(var b=0;b<BOARD_ROWS;b++)if(e[b][a]===
DISC_EMPTY)return b;return null};this.randomThrow=function(){for(var c,d=0;;)if(c=Math.floor(Math.random()*BOARD_COLS),e[BOARD_ROWS-1][c]===DISC_EMPTY){d++;if(50===d)return c;var k=this._getFreeRowFromCol(c);if(k+1<BOARD_ROWS&&!1===this.verifyIfPlayerWins(k+1,c,b,2)&&!1===this.verifyIfPlayerWins(k+1,c,a,2)||k===BOARD_ROWS-1)return c}};this.analyseArrayCols=function(a){if(!a||0===a.length)return[];var b,c=[];for(b=0;b<a.length;b++){for(var f=!1,e=0;e<c;e++)c[e].iValue===a[b]&&(c[e].iCnt++,f=!0);!1===
f&&c.push(Object({iValue:a[b],iCnt:1}))}a=c[0].iCnt;for(b=1;b<c.length;b++)a<c[b].iCnt&&(a=c[b].iCnt);f=[];for(b=0;b<c.length;b++)a===c[b].iCnt&&f.push(c[b].iValue);return f};this.chooseColFromList=function(c){for(var d=0;d<c.length;d++){var f=this._getFreeRowFromCol(c[d]);if(f+1<BOARD_ROWS&&!1===this.verifyIfPlayerWins(f+1,c[d],b,2)&&!1===this.verifyIfPlayerWins(f+1,c[d],a,2))return c[d]}return null};this.strategicThrow=function(){var c=this.verifyProbablyPlayerColWinner(a,0),d=this.verifyProbablyPlayerColWinner(a,
1),e=this.verifyProbablyPlayerColWinner(a,2),h=this.verifyPlayerColWinner(a,0),l=this.verifyPlayerColWinner(a,1);c=this.analyseArrayCols(c);d=this.analyseArrayCols(d);e=this.analyseArrayCols(e);this.analyseArrayCols(h);this.analyseArrayCols(l);h=this.verifyProbablyPlayerColWinner(b,1);l=this.analyseArrayCols(h);h=[];h.push(e);h.push(d);h.push(l);h.push(c);for(c=0;c<h.length;c++)if(0<h[c].length&&(d=this.chooseColFromList(h[c]),null!==d))return d;return this.randomThrow()};this.throwCoin=function(c){e=
c;c=this.verifyPlayerColWinner(a,2);0<c.length?s_oGame.dropDiscByCpu(c[0]):(c=this.verifyPlayerColWinner(b,2),0<c.length?s_oGame.dropDiscByCpu(c[0]):(c=this.analyzelinesOfTwoCoins(b),0<c.length?s_oGame.dropDiscByCpu(c[0]):s_oGame.dropDiscByCpu(this.strategicThrow())))};this.analyzelinesOfTwoCoins=function(a){for(var b=[],c=0;c<BOARD_ROWS;c++)for(var f=0;f<BOARD_COLS;f++)if(e[c][f]===DISC_EMPTY&&(0===c||null!==e[c-1][f]&&e[c-1][f]!==DISC_EMPTY)&&null!==this.analyzeLinesOfTwoHorizontal(c,f,a)){for(var l=
!1,g=0;g<b.length;g++)f===b[g]&&(l=!0);!1===l&&b.push(f)}return b};this.analyzeLinesOfTwoHorizontal=function(a,b,c){if(e[a][b+1]===c&&e[a][b+2]===c&&e[a][b+3]===DISC_EMPTY){if(e[a][b-1]===DISC_EMPTY&&(0===a||e[a-1][b-1]!==DISC_EMPTY))return b;if(e[a][b+4]===DISC_EMPTY&&(0===a||e[a-1][b+4]!==DISC_EMPTY))return b+3}return e[a][b+1]!==c||e[a][b-1]!==c||e[a][b+2]!==DISC_EMPTY||e[a][b-2]!==DISC_EMPTY||0!==a&&(e[a-1][b+2]===DISC_EMPTY||0!==a&&e[a-1][b-2]===DISC_EMPTY)?null:b};this._init()}
function CTiePanel(){var b,a,c,e,f,d;this._init=function(){a=new createjs.Container;b=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));e=b.on("click",function(){});a.addChild(b);c=new createjs.Text(TEXT_TIE," 80px "+PRIMARY_FONT,"#fff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2-62;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=600;a.addChild(c);f=new CGfxButton(CANVAS_WIDTH/2-200,CANVAS_HEIGHT/2+120,s_oSpriteLibrary.getSprite("but_home"),a);f.addEventListener(ON_MOUSE_UP,this._onButHome,
this);d=new CGfxButton(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2+120,s_oSpriteLibrary.getSprite("but_restart"),a);d.addEventListener(ON_MOUSE_UP,this._onButRestart,this);s_oStage.addChild(a);a.alpha=0;createjs.Tween.get(a).to({alpha:1},500,createjs.Ease.cubicOut).call(function(){});setVolume("soundtrack",1)};this.unload=function(){b.on("click",e);s_oStage.removeChild(a);f.unload();d.unload()};this._onButHome=function(){$(s_oMain).trigger("show_interlevel_ad");k.unload();$(s_oMain).trigger("end_session");
s_oGame.onExit()};this._onButRestart=function(){$(s_oMain).trigger("show_interlevel_ad");k.unload();s_oGame.restart()};var k=this;this._init();return this};